
[appendix,obligation=informative]
== PubID patterns

=== Presentation

Generally in this order:

* No update: `{series} {stage} {report number}{part}{edition}({translation})`
* With update: `{series} {stage} {report number}{part}{edition}({translation})/{update} {update number}:{update year}`


=== Full PubID

This is the fully expressed, unambiguous form of the Publication ID.

----
{publisher} {series} {reportnumber} {part | volume)}, {revision} {(draft), optional}
----

[example]
====
National Institute of Standards and Technology Federal Information Processing Standards Publication 199
====

[example]
====
National Institute of Standards and Technology Special Publication 800-27, Revision A
====

[example]
====
National Institute of Standards and Technology Special Publication 800-39 (Second Public Draft)
====

NOTE: Originally described in https://github.com/metanorma/metanorma-nist/issues/98


=== Abbreviated PubID

This form is used in the Authority section.

----
{abbrev(publisher)} {abbrev(series)} {reportnumber} {part | abbrev(volume)}, {abbrev(revision)} {(abbrev(draft)), optional}
----

* `abbrev(series)` represent the abbreviation of the Series title

NOTE: The "update date" (`{update-date}`) is not represented in this syntax and
shall be considered in the final scheme.

[example]
====
"Natl. Inst. Stand. Technol. Spec. Publ. 800-78-4"
====

[example]
====
"Natl. Inst. Stand. Technol. Spec. Publ. 800-116"
====

[example]
====
"Natl. Inst. Stand. Technol. Spec. Publ. 800-57 Part 1, Revision 4"
====

NOTE: Originally from https://github.com/metanorma/metanorma-nist/issues/88


=== Short PubID

The "short form" is used to cite the documents within text.

It is used in these situations:

. Locality references. "In Section 3.2 of SP 800-187..." (the "SP 800-187" is a link).
+
NOTE: NIST pubs are composed of "Sections" not "Clauses"

. A generic document reference. "SP 800-53 describes...". This form does not specify a revision or update date.

. "All parts". "The SP 800-57 subseries describes key management...".

NOTE: Currently, citations within documents can take form of say,
"NISTIR 6885 2003 Edition (February 2003)", which is rather long in length causing
disruption in reading flow.

The syntax for a Short PubID could be:

----
{abbrev(series)} {reportnumber} {abbrev(volume)} {abbrev(revision)} {(draft), optional} {edition, optional}
----

NOTE: For FIPS, `{reportnumber}` is the full FIPS number, including revision, e.g.,
`140-2`.

NOTE: Originally from https://github.com/metanorma/metanorma-nist/issues/88.

Short form date:

* `Month YYYY`

[example]
====
NIST SP 800-53r4 (20152201) supersedes NIST SP 800-53r4 (20140115)
====

[example]
====
NIST SP 800 63A (December 2017) supersedes NIST SP 800-63A
====

[example]
====
NIST SP 800 57 Part 1 Revision 4 supersedes NIST SP 800-57 Part 1 Revision 3 ("Rev." is also accepted, and converted to "Revision")
====

[example]
====
NIST SP 800 160 Volume 1 supersedes NIST SP 800-160 (20180103) ("Vol." is also accepted, and converted to "Volume")
====

[example]
====
Undated form "NIST SP 800 53r4"
====

Strip Revision and Date from title, only if the Revision and Date are unique for
each document number. These are identified as "Rev. {number}", "Revision {number}" and
"(Month YYYY)", whichever comes first.

[[patterns-mr]]
=== Machine-readable PubID

PubID form intended for machine parsing. Special care is taken to eliminate
empty spaces and limit the character set to alphanumeric characters.

The syntax could be:

----
{publisher}.{series}.[{stage}.]{reportnumber}.{part}.{revision}.[{lang}.]{update-date}
----

----
{publisher}.{series}.[{stage}.]{reportnumber}.{part}.{revision}.[{lang}.][{update}]{update-date}
----

Generally, this rule should be able to uniquely identify an edition of a document.

* `{part}`
** Part
*** A "Part 1" document is encoded as "pt1";
*** When a letter part is indicated, e.g. "800-63A", we should keep it as part of
  the reportnumber, but also explicitly indicate the "pt", e.g.
  `NIST.SP.800-38A.pt-A`

** Volumes
*** "Volume 1" is encoded as "v1";

* `{revision}`
** "Revision 1" is encoded as "r1"

** If a superseding edition is a full revision, it will get the next Rev. #.
** If a superseding edition is just an errata update, we use the update date
from the title page ("includes updates as of ...") to uniquely identify this
edition. Preferably in the `-yyyymmdd` format.

* `{update}`
** "Update 1" is encoded as "u1"

Some examples:

[example]
====
`NIST.SP.800-53r4-20152201` supersedes `NIST.SP.800-53r4-20140115`
====

[example]
====
`NIST.SP.800-63A-20171201` supersedes `NIST.SP.800-63A`
====

[example]
====
`NIST.SP.800-57pt1r4` supersedes `NIST.SP.800-57pt1r3`
====

[example]
====
`NIST.SP.800-160v1` supersedes `NIST.SP.800-160-20180103`
====

[example]
====
`NIST.IR.8204.u1-2019` supersedes `NIST.IR.8204`
====

[example]
====
The undated form is `NIST.SP.800-53r4`
====

NOTE: Originally from https://github.com/metanorma/metanorma-nist/issues/88.
